LogoFeild = "//a/img[@alt='Plum Fuse']"
createappButton = "//a[@id='link-create'][contains(text(),'Create an App')]"
popupbutton = "//*[@id=\"intro-dialog-cont\"]/div[2]/button"
newpagebutton = "//*[@id=\"add-page\"]"
createapppage = "//*[@id=\"create-dialog\"]/form/p/input"
createbutton = "/html/body/div[20]/div[3]/button[1]"
messagingtabbutton = "//*[@id=\"accordion\"]/h3[4]/a"
sendansmsdrag = "//*[@id=\"accordion\"]/div[4]/ul/li[3]"
startbuttonsource = "//div[@id='module-1']/div/div[@class='syn-node ui-draggable syn-node-active']"
sendansmsdestinationnotsent = "//div[@id='module-2']/div/div[@class='syn-receptor ui-droppable syn-receptor-north ui-draggable syn-receptor-draggable']"
phonenumberinput = "//*[@id=\"module-2\"]/div[1]/div[3]/div/div[1]/div[2]/textarea"
messagetextvariableinput = "//*[@id=\"module-2\"]/div[1]/div[3]/div/div[2]/div/table/tbody/tr/td[1]/div/textarea"
sendanemaildrag = "//*[@id=\"accordion\"]/div[4]/ul/li[2]"
sendansmssource = "//div[@id='module-2']//div[@class='panel-nodes-attached inner']/div[@class='syn-node syn-node-attached-e ui-draggable syn-node-active']"
sendanemaildestination = "//div[@id='module-3']//div[@class='syn-receptor ui-droppable syn-receptor-north ui-draggable syn-receptor-draggable']"
smtphost = "//*[@id=\"module-3\"]/div[1]/div[3]/div/div[1]/div[1]/div[2]/input"
port = "//*[@id=\"module-3\"]/div[1]/div[3]/div/div[1]/div[2]/div[2]/input"
Username = "//*[@id=\"module-3\"]/div[1]/div[3]/div/div[1]/div[3]/div[2]/input"
Password = "//*[@id=\"module-3\"]/div[1]/div[3]/div/div[1]/div[4]/div[2]/input"
From = "//*[@id=\"module-3\"]/div[1]/div[3]/div/div[2]/div[1]/div[2]/div/textarea"
To = "//*[@id=\"module-3\"]/div[1]/div[3]/div/div[2]/div[2]/div[2]/div/textarea"
Subject = "//*[@id=\"module-3\"]/div[1]/div[3]/div/div[2]/div[3]/div[2]/div/textarea"
sendanemailmsgtextvariable = "//*[@id=\"module-3\"]/div[1]/div[3]/div/div[3]/div/div/table/tbody/tr/td[1]/div/textarea"
basicbutton = "//*[@id=\"accordion\"]/h3[1]/a"
hanguporexit = "//*[@id=\"accordion\"]/div[1]/ul/li[1]"
sendansmssourcesent = "//div[@id='module-2']//div[@class='panel-nodes-attached inner']/div[@class='syn-node syn-node-attached-w ui-draggable syn-node-active']"
hanguporexitdestination = "//div[@id='module-4']//div[@class='syn-receptor ui-droppable syn-receptor-north ui-draggable syn-receptor-draggable']"
sendanemailsentsource = "//div[@id='module-3']//div[@class='panel-nodes-attached inner']/div[@class='syn-node syn-node-attached-w ui-draggable syn-node-active']"
hanguporexitdestinationforsentemail = "//div[@id='module-5']//div[@class='syn-receptor ui-droppable syn-receptor-north ui-draggable syn-receptor-draggable']"
sendanemailnotsentsource = "//div[@id='module-3']//div[@class='panel-nodes-attached inner']/div[@class='syn-node syn-node-attached-e ui-draggable syn-node-active']"
hanguporexitdestinationfornotsentemail = "//div[@id='module-6']//div[@class='syn-receptor ui-droppable syn-receptor-north ui-draggable syn-receptor-draggable']"
